### ISSUE TITLE
Error on method getPost

### ISSUE THREAD

**Issue by mesilov** [amplifr/amplifr-php#4]
http://docs.amplifr.apiary.io/#reference/posts/apiv1projectsprojectidpostspostid/get-a-post?console=1

When send request to API, i see a 500: Internal Server Error

GET https://amplifr.com/api/v1/projects/1377/posts/1005916/ — error URL

**Comment by gazay** [comment]
@mesilov а где ты этот пост id получил? Мне возвращает 404

**Comment by mesilov** [comment]
@gazay 
1.  Публикуем пост через API, нам возвращается его ID

`
id: 1021407
url: https://amplifr.com
post time: 2016-09-28T23:58:33+0300
text: Hello world! #1830518
states: Array
(
    [60867] => publishing
)
`
1.  Убеждаемся, что в админке он есть 
   https://yadi.sk/i/v17h8VD_vrzsG
2. Проверяем визуально
   https://twitter.com/b24io/status/781237267591532544
3. Пытаемся получить по нему инфу через API и получаем ошибку

`
PHP Fatal error:  Uncaught exception 'Amplifr\Exceptions\IoAmplifrException' with message 'network error, http code: 500' in /home/bitrix/ext_www/mesilov.b24.io/dev/amplifr/amplifr-php/src/Amplifr/Amplifr.php:697
Stack trace:
#0 /home/bitrix/ext_www/mesilov.b24.io/dev/amplifr/amplifr-php/src/Amplifr/Amplifr.php(668): Amplifr\Amplifr->handleNetworkErrors()
#1 /home/bitrix/ext_www/mesilov.b24.io/dev/amplifr/amplifr-php/src/Amplifr/Amplifr.php(394): Amplifr\Amplifr->executeApiRequest('/projects/1377/...', 'GET')
#2 /home/bitrix/ext_www/mesilov.b24.io/dev/amplifr/test.php(68): Amplifr\Amplifr->getPost(1377, 1021407)
#3 {main}
  thrown in /home/bitrix/ext_www/mesilov.b24.io/dev/amplifr/amplifr-php/src/Amplifr/Amplifr.php on line 697

`

**Comment by mesilov** [comment]
@gazay 
Если выполниь запрос на получение списка постов, то он будет в ответе с сервера

`
     array(21) {
        ["id"]=>
        int(1021407)
        ["url"]=>
        string(19) "https://amplifr.com"
        ["time"]=>
        int(1475096313)
        ["text"]=>
        string(21) "Hello world! #1830518"
        ["author"]=>
        int(1598)
        ["clicks"]=>
        int(0)
        ["likes"]=>
        int(0)
        ["shares"]=>
        int(0)
        ["comments"]=>
        int(0)
        ["clickCounting"]=>
        bool(true)
        ["uniqueViews"]=>
        int(0)
        ["fanUniqueViews"]=>
        int(0)
        ["totalViews"]=>
        int(0)
        ["videoPlays"]=>
        int(0)
        ["errors"]=>
        array(0) {
        }
        ["states"]=>
        array(1) {
          [60867]=>
          string(9) "published"
        }
        ["socials"]=>
        array(1) {
          [0]=>
          int(60867)
        }
        ["subforms"]=>
        array(0) {
        }
        ["publications"]=>
        array(1) {
          [60867]=>
          string(51) "https://twitter.com/b24io/status/781237267591532544"
        }
        ["attachments"]=>
        array(1) {
          [0]=>
          string(13) "image:1390145"
        }
        ["previews"]=>
        array(1) {
          [0]=>
          string(111) "https://imgcdn2.amplifr.com/images/social_images/001/390/145/img.jpg?s=53cdd9cf9ff3ea5d0064dbd68e762cf9f2178487"
        }
      }

`

**Comment by gazay** [comment]
Ага, ошибка, ща поправлю

**Comment by gazay** [comment]
Фиксед

**Comment by mesilov** [comment]
https://github.com/amplifr/amplifr-php/commit/4e0becb9968bd8066b3228594ad6d70b48207690
