### ISSUE TITLE
Add repo to TRAVIS CI

### ISSUE THREAD

**Issue by mesilov** [amplifr/amplifr-php#5]
travis config in repo https://github.com/amplifr/amplifr-php/blob/dev/.travis.yml
add branch master and dev 
see https://travis-ci.org/

**Comment by gazay** [comment]
@xnutsive аналогично, тревис мне не показывает amplifr

**Comment by natikgadzhi** [comment]
https://travis-ci.org/amplifr/amplifr-php/ Готово.
