### ISSUE TITLE
Add Packagist  service hook in repo settings

### ISSUE THREAD

**Issue by mesilov** [amplifr/amplifr-php#6]
GitHub Service Hook

Enabling the Packagist service hook ensures that your package will always be updated instantly when you push to GitHub.

To do so you can:

Go to your GitHub repository
Click the "Settings" button
Click "Webhooks & Services"
Add a "Packagist" service, and configure it with your API token, plus your Packagist username
Check the "Active" box and submit the form
You can then hit the "Test Service" button to trigger it and check if Packagist removes the warning about the package not being auto-updated.

see API token in facebook messenger

**Comment by gazay** [comment]
@xnutsive только ты можешь это сделать

**Comment by natikgadzhi** [comment]
Кажется сделал.
